#!/bin/bash
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.a
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.b
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.a,Y.b
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Z.a
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.a,Z.a
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.b,Z.a
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.a,Y.b,Z.a
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Z.b
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.a,Z.b
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.b,Z.b
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.a,Y.b,Z.b
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Z.a,Z.b
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.a,Z.a,Z.b
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.b,Z.a,Z.b
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.a,Y.b,Z.a,Z.b
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=k
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.a,k
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.b,k
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.a,Y.b,k
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Z.a,k
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.a,Z.a,k
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.b,Z.a,k
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.a,Y.b,Z.a,k
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Z.b,k
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.a,Z.b,k
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.b,Z.b,k
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.a,Y.b,Z.b,k
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Z.a,Z.b,k
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.a,Z.a,Z.b,k
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.b,Z.a,Z.b,k
qsub r_submit.sh dimension_analysis-run.r --run=2012_06_20 --evolvable=Y.a,Y.b,Z.a,Z.b,k
